repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer

# repo is not properly annotated
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.8.0
#     hooks:
#     -   id: mypy
