CUDA_VISIBLE_DEVICES=3 python train_brats2021.py \
    --comment train \
    --gpus 0 \
    --seed 1000 \
    --amp \
    --num_workers 2 \
    --exp_dir exps \
    --dataset brats2021 \
    --cases_split data/split/brats2021_split_fold0.csv \
    --input_channels 4 \
    --epochs 3 \
    --batch_size 8 \
    --lr 1e-3 \
    --optim adamw \
    --wd 1e-4 \
    --scheduler warmup_cosine \
    --warmup_epochs 5 \
    --num_classes 3 \
    --unet_arch multiencoder_unet \
    --block plain \
    --channels_list 32 64 128 256 320 320 \
    --patch_size 128 128 32 \
    --pos_ratio 1.0 \
    --neg_ratio 1.0 \
    --save_model \
    --save_pred \
    --eval_freq 1 \
    --print_freq 5
